# Generated by Django 3.0.4 on 2020-04-06 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_auto_20200406_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ced_empleado', models.IntegerField()),
                ('nom_empleado', models.CharField(max_length=30)),
                ('tipo_empleado', models.CharField(choices=[('T', 'TIQUETES'), ('S', 'SNACKS')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField()),
                ('cod_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_producto', models.IntegerField()),
                ('ced_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_silla', models.CharField(choices=[('G', 'GENERAL'), ('P', 'PREFERENCIAL')], max_length=1)),
                ('cod_reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.Reserva')),
                ('cod_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=3, max_digits=15)),
                ('nom_producto', models.CharField(max_length=20)),
                ('cod_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('cod_factura', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tipo_factura', models.CharField(choices=[('RE', 'RESERVA'), ('PR', 'PRODUCTO')], max_length=2)),
                ('val_factura', models.DecimalField(decimal_places=3, max_digits=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('ced_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Cliente')),
                ('ced_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Empleado')),
            ],
        ),
    ]
