# Generated by Django 3.0.4 on 2020-04-10 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ced_cliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nom_cliente', models.CharField(max_length=30, verbose_name='Nombre')),
                ('correo_cliente', models.CharField(max_length=20, verbose_name='Correo')),
                ('puntos_cliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Multiplex',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo multiplex')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('numero_salas', models.IntegerField(verbose_name='Número de salas')),
                ('imagen_cc', models.ImageField(null=True, upload_to='media', verbose_name='Imagen cc')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo película')),
                ('nom_pelicula', models.CharField(max_length=30, verbose_name='Nombre')),
                ('duracion_pelicula', models.TimeField(verbose_name='Duracion película')),
                ('clasificacion', models.CharField(choices=[('AA', 'PUBLICO INFANTIL'), ('A', 'TODO PUBLICO'), ('B', 'ADOLESCENTES DE 12'), ('B15', 'ADOLESCENTES DE 15'), ('C', 'ADULTOS 18 AÑOS'), ('D', 'ADULTOS')], max_length=3, verbose_name='Calsificación película')),
                ('imagen_pelicula', models.ImageField(upload_to='media', verbose_name='Imagen película')),
                ('trailer', models.URLField(blank=True, verbose_name='Trailer película')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo sala')),
                ('cant_sillas', models.IntegerField(verbose_name='Cantidad de sillas')),
                ('estado_sala', models.CharField(choices=[('HA', 'HABILITADA'), ('IN', 'INHABILITADA')], max_length=3, verbose_name='Estado sala')),
                ('cod_multi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Multiplex', verbose_name='Codigo múltiplex')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_producto', models.IntegerField(verbose_name='Cantidad de productos')),
                ('ced_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Codigo silla')),
                ('tipo_silla', models.CharField(choices=[('G', 'GENERAL'), ('P', 'PREFERENCIAL')], max_length=1, verbose_name='Tipo de silla')),
                ('estado_silla', models.IntegerField(default=0, verbose_name='Estado silla')),
                ('cod_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Sala', verbose_name='Codigo sala')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(verbose_name='Fecha de reserva')),
                ('cod_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo proyección')),
                ('horario', models.DateTimeField(verbose_name='Hora película')),
                ('cod_pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.Pelicula', verbose_name='Codigo película')),
                ('cod_sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.Sala', verbose_name='Codigo Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Valor unitario')),
                ('nom_producto', models.CharField(max_length=20, verbose_name='Nombre del producto')),
                ('imagen_producto', models.ImageField(upload_to='media', verbose_name='imagen del producto')),
                ('cod_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Venta', verbose_name='codigo de venta')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('cod_factura', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tipo_factura', models.CharField(choices=[('RE', 'RESERVA'), ('PR', 'PRODUCTO')], max_length=2)),
                ('val_factura', models.DecimalField(decimal_places=3, max_digits=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('ced_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Cliente')),
                ('ced_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
