# Generated by Django 3.0.4 on 2020-04-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_cliente_empleado_factura_multiplex_pelicula_producto_proyeccion_reserva_sala_silla_user_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='ced_cliente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='ced_vendedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cod_venta',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cod_vendedor',
        ),
        migrations.RemoveField(
            model_name='silla',
            name='cod_reserva',
        ),
        migrations.RemoveField(
            model_name='silla',
            name='cod_sala',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ced_vendedor',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Silla',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
